WITH UNREGISTERED_EMPLOYEES AS 
( 
SELECT  
    EMP.EMPLOYEE_ID, 
    DEPT.DEPARTMENT_NAME AS "DEPTNAMES"  
FROM  
    HR.DEPARTMENTS DEPT, 
    HR.EMPLOYEES EMP 
WHERE 
    (EMP.DEPARTMENT_ID(+))=(DEPT.DEPARTMENT_ID)  
    AND (EMP.EMPLOYEE_ID IS NULL) 
)     
SELECT 
    SUBSTR(DEPARTMENT_NAME,5,1) AS "FIFTH LETTER" 
FROM 
    HR.DEPARTMENTS, 
    UNREGISTERED_EMPLOYEES 
WHERE 
    (DEPARTMENT_NAME)=(DEPTNAMES)
