WITH HIGHEST_SALARY AS 
( 
SELECT 
    MAX(EMP.SALARY) AS "HIGHEST_SALARIES",DEPT.DEPARTMENT_NAME AS "DEPTNAME" 
FROM 
    HR.DEPARTMENTS DEPT, 
    HR.EMPLOYEES EMP 
WHERE 
    (DEPT.DEPARTMENT_ID)=(EMP.DEPARTMENT_ID) 
GROUP BY 
    DEPT.DEPARTMENT_NAME 
) 
SELECT  
    EMP.LAST_NAME,EMP.DEPARTMENT_ID,EMP.SALARY 
FROM 
    HR.EMPLOYEES EMP, 
    HR.DEPARTMENTS DEPT, 
    HIGHEST_SALARY 
WHERE 
    (EMP.DEPARTMENT_ID)=(DEPT.DEPARTMENT_ID) AND (DEPT.DEPARTMENT_NAME)=(DEPTNAME) 
    AND (EMP.SALARY)=(HIGHEST_SALARIES) 
