WITH HIGHEST_SALARY AS 
( 
SELECT 
    MAX(EMP.SALARY) AS "HIGHEST_SALARIES",DEPT.DEPARTMENT_NAME AS "DEPTNAME" 
FROM 
    HR.DEPARTMENTS DEPT, 
    HR.EMPLOYEES EMP 
WHERE 
    (DEPT.DEPARTMENT_ID)=(EMP.DEPARTMENT_ID) 
GROUP BY 
    DEPT.DEPARTMENT_NAME 
) 
SELECT  
    EMP.LAST_NAME,EMP.DEPARTMENT_ID,EMP.SALARY 
FROM 
    HR.EMPLOYEES EMP, 
    HR.DEPARTMENTS DEPT, 
    HIGHEST_SALARY 
WHERE 
    (EMP.DEPARTMENT_ID)=(DEPT.DEPARTMENT_ID) AND (DEPT.DEPARTMENT_NAME)=(DEPTNAME) 
    AND (EMP.SALARY)=(HIGHEST_SALARIES) 

--------------------Other Versions:Analytic Functions Used-------------------

--NTH VALUE--

WITH HIGHEST_SALARY AS  
(  
SELECT  
    EMP.FIRST_NAME,EMP.LAST_NAME,EMP.EMPLOYEE_ID,DEPT.DEPARTMENT_NAME,EMP.SALARY,NTH_VALUE(EMP.SALARY,1) OVER(PARTITION BY DEPT.DEPARTMENT_NAME 
    ORDER BY EMP.SALARY DESC RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS FIRST_HIGHEST_SALARY 
FROM  
    HR.DEPARTMENTS DEPT,  
    HR.EMPLOYEES EMP  
WHERE  
    (DEPT.DEPARTMENT_ID)=(EMP.DEPARTMENT_ID)  
 
)  
 
SELECT * FROM HIGHEST_SALARY 
WHERE FIRST_HIGHEST_SALARY=SALARY

--ROW_NUMBER()--

WITH HIGHEST_SALARY AS  
(  
SELECT  
    EMP.LAST_NAME,EMP.EMPLOYEE_ID,DEPT.DEPARTMENT_NAME,EMP.SALARY,ROW_NUMBER() OVER(PARTITION BY DEPT.DEPARTMENT_ID 
    ORDER BY EMP.SALARY) AS SALARY_RANK 
     
FROM  
    HR.DEPARTMENTS DEPT,  
    HR.EMPLOYEES EMP  
WHERE  
    (DEPT.DEPARTMENT_ID)=(EMP.DEPARTMENT_ID)  
 
)  
 
SELECT * FROM HIGHEST_SALARY 
WHERE SALARY_RANK=1

--RANK()--


WITH HIGHEST_SALARY AS  
(  
SELECT  
    EMP.LAST_NAME,EMP.EMPLOYEE_ID,DEPT.DEPARTMENT_NAME AS "DEPTNAME",RANK() OVER(PARTITION BY DEPT.DEPARTMENT_ID 
    ORDER BY EMP.SALARY DESC) AS SALARY_RANK 
     
FROM  
    HR.DEPARTMENTS DEPT,  
    HR.EMPLOYEES EMP  
WHERE  
    (DEPT.DEPARTMENT_ID)=(EMP.DEPARTMENT_ID)  
 
)  
 
SELECT * FROM HIGHEST_SALARY 
WHERE SALARY_RANK=1


--DENSE_RANK()--


WITH HIGHEST_SALARY AS  
(  
SELECT  
    EMP.LAST_NAME,EMP.EMPLOYEE_ID,DEPT.DEPARTMENT_NAME AS "DEPTNAME" ,DENSE_RANK() OVER(PARTITION BY DEPT.DEPARTMENT_ID 
    ORDER BY EMP.SALARY DESC) AS SALARY_RANK 
     
FROM  
    HR.DEPARTMENTS DEPT,  
    HR.EMPLOYEES EMP  
WHERE  
    (DEPT.DEPARTMENT_ID)=(EMP.DEPARTMENT_ID)  
 
)  
 
SELECT * FROM HIGHEST_SALARY 
WHERE SALARY_RANK=1
